categories:
  - title: "ğŸš€ Feature"
    labels:
      - feature
  - title: "ğŸ› Bug Fixes"
    labels:
      - bug
  - title: "ğŸ“– Docs"
    labels:
      - documentation
autolabeler:
  - label: "feature"
    branch:
      - "/^feat/i"
      - "/^feature/i"
  - label: "bug"
    branch:
      - "/^fix/"
  - label: "documentation"
    branch:
      - "/^docs/"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
  default: "patch"

template: |
  ## Changes

  $CHANGES
