categories:
  - title: "ğŸš€ Feature"
    labels:
      - feature
  - title: "ğŸ› Bug Fixes"
    labels:
      - bug
  - title: "ğŸ“– Docs"
    labels:
      - docs
autolabeler:
  - label: "feature"
    branch:
      - "/^feat/i"
      - "/^feature/i"
  - label: "bug"
    branch:
      - "/^fix/"
  - label: "docs"
    branch:
      - "/^docs/"
template: |
  ## Changes

  $CHANGES

